name: linux static analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false

    - name: Install ninja, dependencies (Poco), clang
      shell: bash
      run: sudo apt install ninja-build libpoco-dev

    - name: Configure CMake for static analysis
      shell: cmake -P {0}
      run: |
        execute_process(
          COMMAND cmake
            -S ${{ github.workspace }}
            -B build
            -D CMAKE_BUILD_TYPE=Debug
            -D CMAKE_CXX_COMPILER=g++
            -G Ninja
            -D STATIC_ANALYSIS=ON
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Failed to build project")
        endif()

    - name: Build + run static analysis
      shell: bash
      run: cmake --build build
