name: windows build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup vcpkg
      shell: pwsh
      run: .\tools\vcpkg\bootstrap-vcpkg.bat

    - name: Install dependencies (Poco, GTest) with vcpkg
      shell: pwsh
      run: .\tools\vcpkg\vcpkg.exe install poco[netssl] gtest

    - name: Configure CMake
      shell: cmake -P {0}
      run: |
        execute_process(
          COMMAND cmake
            -S .
            -B build
            -D CMAKE_CXX_COMPILER=cl
            --toolchain ./tools/vcpkg/scripts/buildsystems/vcpkg.cmake
            -D CMAKE_INSTALL_PREFIX=./build/install
            -D BUILD_TESTING=ON
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Failed to build project")
        endif()

    - name: Build Debug
      run: cmake --build build --config Debug

    - name: Run tests
      run: ctest -VV --test-dir build

    - name: Install
      run: cmake --build build --config Debug -t install

    - name: Remove install artifacts
      shell: pwsh
      run: |
        Remove-Item .\build\install\ -Recurse -Force

    - name: Build Release
      run: cmake --build build --config Release

    - name: Run tests
      run: ctest -VV --test-dir build

    - name: Install
      run: cmake --build build --config Release -t install
